config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root 'categories#home', as: :authenticated_root
  end

  unauthenticated do
    root 'categories#index', as: :unauthenticated_root
  end

   devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end

  resources :categories, only: %i[index home new create destroy] do
    get :home, on: :collection
    resources :transacts, only: %i[index new create]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.admin?
      can :manage, :all
    else
      can :manage, Category, user_id: user.id
      can :manage, Transact, user_id: user.id
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :transact_categories, dependent: :destroy
  has_many :transacts, through: :transact_categories

  validates :user_id, presence: true
  validates :name, presence: true
  validates :icon, presence: true
end

app/models/transact.rb
class Transact < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :transact_categories, dependent: :destroy
  has_many :categories, through: :transact_categories

  validates :author_id, presence: true
  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validate :at_least_one_category

  private

  def at_least_one_category
    errors.add(:base, 'Please select at least one category') if categories.empty?
  end
end

app/models/transact_category.rb
class TransactCategory < ApplicationRecord
  belongs_to :transact
  belongs_to :category

  validates :category_id, uniqueness: { scope: :transact_id }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :transacts, foreign_key: 'author_id', dependent: :destroy
  has_many :categories, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?
  before_action :set_current_user

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def set_current_user
    @current_user = current_user
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index; end

  def home
    @categories = current_user.categories
  end

  def new
    @category = Category.new
    @choices = [
      ['🛒'], ['🍽️'],
      ['⚽'], ['📐'],
      ['🚗'], ['🛋️'],
      ['🍔'], ['⚕️'],
      ['🎮'], ['💻'],
      ['🌿'], ['🎨'],
      ['💼'], ['📱']
    ]
  end

  def create
    @user = current_user
    @category = @user.categories.new(categories_params)
    @category.user = @user
    if @category.save
      redirect_to home_categories_path, notice: 'Category was successfully created'
    else
      redirect_to new_category_path, alert: 'Can\'t create a new category'
    end
  end

  private

  def categories_params
    params.require(:category).permit(:name, :icon).merge(user: current_user)
  end
end

app/controllers/transacts_controller.rb
class TransactsController < ApplicationController
  before_action :authenticate_user!
  def index
    @category = Category.find(params[:category_id])
    @transacts = @category.transacts.order(created_at: :desc)
    @total = @transacts.map(&:amount).sum
  end

  def new
    @category = Category.find(params[:category_id])
    @categories = Category.all
    @transact = Transact.build
  end

  def create
    @user = current_user
    @transact = @user.transacts.build(transacts_params)
    @category = Category.find(params[:category_id])

    if @transact.save
      category_ids = params[:transact][:category_ids] || @category
      category_ids.each do |category_id|
        TransactCategory.create(category_id:, transact_id: @transact.id)
      end
      redirect_to category_transacts_path(category_id: @category),
                  notice: 'Transaction was successfully created.'
    else
      @category = Category.find(params[:category_id])
      @categories = Category.all
      render :new, alert: 'Transaction can\'t be created'
    end
  end

  private

  def transacts_params
    params.require(:transact).permit(:name, :amount, category_ids: [])
  end
end

app/controllers/users_controller.rb
# controllers/users_controller.rb

class UsersController < ApplicationController
  before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/transacts_helper.rb
module TransactsHelper
end

app/views/categories/home.html.erb
<div>
 <% @header = 'CATEGORIES' %>
 	  <% if @categories.empty?%>
      <p>You don't have any categories yet !!</p>
        <% else %>
          <ul>
              <% @categories.each do |categ| %>
                  <%= link_to category_transacts_path(category_id: categ.id),class:'link' do %>
                      <li class='categ'>
                          <div><%= categ.icon %>
                          <%= categ.name %></div>
                          <div>$ <%= categ.transacts.sum(:amount) %>
                      </li>
                  <% end %>
              <% end %>
          </ul>
        <% end %>
        <div class='new-btn'> 
  <%= link_to "Add a new category", new_category_path, class:'add-new-btn link'%>
  </div>
</div>

app/views/categories/index.html.erb
<div class='splash text-white bg-main-color'>
  <h1>Budget App</h1>
  <div class='btns'>
    <%= link_to "Log In", new_user_session_path ,class:'btn'%>
    <%= link_to "Sign up", new_user_registration_path,class:'btn'%>
  </div>
</div>

app/views/categories/new.html.erb
<div>
 <% @header = "NEW CATEGORY" %>
  <%= form_with model: @category, url: categories_path do |form| %>
          <div class="main-field">
            <%= form.text_field :name, placeholder: "New Category", required: true, class:"text-field"%>
            <%= form.select :icon, options_for_select(@choices, selected: @category.icon), { prompt: "Select an icon" }, required: true,class:'text-field'%>
          </div>
    <%= form.submit "Save", class:'save-btn'%>
  <% end %>
</div>

app/views/layouts/_header.html.erb
  <div class="header bg-main-color text-white">
    <div>
    <% if back %>
     <% if request.path.include?('/categories/new') %>
       <%= link_to(home_categories_path) do %>
        <% end %>
       <% elsif request.path == category_transacts_path %>
       <%= link_to(home_categories_path) do %>
       <% end %>
      <% end %>	     
    <% else %>
     <%= link_to("javascript:history.back()") do %>
     <svg fill="#ffffff" height="24px" width="24px" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 492 492" xml:space="preserve" stroke="#ffffff"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <g> <g> <path d="M198.608,246.104L382.664,62.04c5.068-5.056,7.856-11.816,7.856-19.024c0-7.212-2.788-13.968-7.856-19.032l-16.128-16.12 C361.476,2.792,354.712,0,347.504,0s-13.964,2.792-19.028,7.864L109.328,227.008c-5.084,5.08-7.868,11.868-7.848,19.084 c-0.02,7.248,2.76,14.028,7.848,19.112l218.944,218.932c5.064,5.072,11.82,7.864,19.032,7.864c7.208,0,13.964-2.792,19.032-7.864 l16.124-16.12c10.492-10.492,10.492-27.572,0-38.06L198.608,246.104z"></path> </g> </g> </g></svg>
  <% end %>
      <% end %>
    </div>
    <div>
      <%= @header %>
    </div>
        <!-- Logout button -->
        <form>
          <%= link_to "Log out", destroy_user_session_path, method: :delete ,class:'text-white link'%>
        </form>

      </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "style", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
   </head>

  <body>
     <% if user_signed_in? %>
        <%= render "layouts/header", locals: { header: @header }, back: false %>
     <p class="text-green f-15"><%= notice %></p>
       <p class="text-red f-15"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/transacts/index.html.erb
<div>
  <% @header = "TRANSACTIONS" %>
<div>
  <% if @transacts.empty?%>
    <p>You don't have any transactions yet !!</p>
  <% else %>
    <ul>
      <li class="categ-trans">
          <div class="tran-name text-color">
            <div><%= @category.icon %>
            <%= @category.name %></div>
          </div>
          <div>
            <div class="text-main-color f-15">Total amount: $<%= number_with_delimiter(@total) %></div>
          </div> 
      </li>
      <% @transacts.each do |tran| %>
        <li> 
          <div class='list'>
              <svg width="50px" height="50px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round" stroke="#CCCCCC" stroke-width="0.048"></g><g id="SVGRepo_iconCarrier"> <path opacity="0.4" d="M6.73022 19.7C7.55022 18.82 8.80023 18.89 9.52023 19.85L10.5302 21.2C11.3402 22.27 12.6502 22.27 13.4602 21.2L14.4702 19.85C15.1902 18.89 16.4402 18.82 17.2602 19.7C19.0402 21.6 20.4902 20.97 20.4902 18.31V7.04C20.4902 3.01 19.5502 2 15.7702 2H8.21024C4.43024 2 3.49023 3.01 3.49023 7.04V18.3C3.50023 20.97 4.96022 21.59 6.73022 19.7Z" fill="#3778c3"></path> <path d="M14.75 10.75H9.25C8.84 10.75 8.5 10.41 8.5 10C8.5 9.59 8.84 9.25 9.25 9.25H14.75C15.16 9.25 15.5 9.59 15.5 10C15.5 10.41 15.16 10.75 14.75 10.75Z" fill="#3778c3"></path> </g></svg>
              <div class="tran-name text-color">
                <span><%= tran.name %></span>
              <span class='date-span'><%= tran.created_at.strftime("%d %B '%Y, %R") %></span>
          </div>
          
              <span class="text-main-color">$<%=  number_with_delimiter(tran.amount)%></span>
          </div>
        </li>
      <% end %>
    </ul>
  <% end %>
  <div class='new-btn'> 
  <%= link_to "Add a new Transaction", new_category_transact_path(@category), class:'add-new-btn link'%>
  </div>
</div>

app/views/transacts/new.html.erb
<div>
 <% @header = "NEW TRANSACTION" %>
  <%= form_with(model: [@category,@transact], url: category_transacts_path(@category) , method: :post,id: 'transact-form') do |form| %>
  <div class='main-field'>
    <%= form.text_field :name, placeholder: "Name", required: true, class: 'text-field' %>
    <%= form.number_field :amount, placeholder: "Amount (USD)", required: true, class: 'text-field' %>

    <div class="checkboxes">
      <div>Select Categories</div>
      <% @categories.each_with_index do |catg, index| %>
        <%= check_box_tag 'transact[category_ids][]', catg.id %>
        <%= label_tag "transact_category#{catg.id}", catg.name %> <br>
      <% end %>
    </div>
  </div>

  <%= form.submit "Save", class: 'save-btn' %>
<% end %>
</div>